# -*- mode: ruby -*-
# vi: set ft=ruby :
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

Vagrant.configure(2) do |config|

  config.vm.synced_folder "/home/jeqo/oracle/fmw/installers/", "/srv/files", mount_options: ["dmode=777,fmode=776"]

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "test.yml"
    ansible.galaxy_role_file = "roles.yml"
  end

  config.vm.provider :virtualbox do |vb|
    vb.cpus = 1
    vb.memory = "1024"
  end

  config.vm.define "test01" do |node|
    node.vm.box = "jeqo/oracle-jdk-8-centos7"
  end

  config.vm.define "test02" do |node|
    node.vm.box = "jeqo/oracle-jdk-8-centos7"
  end

  config.vm.define "test03" do |node|
    node.vm.box = "jeqo/oracle-jdk-7-centos7"
  end
end
